global:
  # set the threshold for all loggers
  logLevel: INFO
local:
  logLevel: INFO
  logToStdout: False
remote:
  active: True
  url: "${OPEN_OBSERVE_LOGS_URL}"
  authorization: "${OPEN_OBSERVE_LOGS_AUTH_HEADER_VALUE}"
  logLevel: WARNING
